"use client";

import { Download, CheckCircle, AlertTriangle, Clock, Zap, FileText, ShieldCheck } from "lucide-react";
import { AuditResult, SEVERITY_CONFIG, RISK_CONFIG, Severity } from "../types";
import FindingCard from "./FindingCard";

export default function AuditReport({ result }: { result: AuditResult }) {
  const riskCfg = RISK_CONFIG[result.riskScore];
  const severityOrder: Severity[] = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];
  const sorted = [...result.findings].sort(
    (a, b) => severityOrder.indexOf(a.severity) - severityOrder.indexOf(b.severity)
  );
  const counts = result.findings.reduce((acc, f) => {
    acc[f.severity] = (acc[f.severity] || 0) + 1;
    return acc;
  }, {} as Record<Severity, number>);

  const handleExport = () => {
    const lines = [
      "═".repeat(52),
      "  HAWKEYE SECURITY AUDIT REPORT",
      "═".repeat(52),
      `  Contract  : ${result.contractName}`,
      `  Risk Level: ${result.riskScore}`,
      `  Generated : ${new Date(result.timestamp).toLocaleString()}`,
      `  Findings  : ${result.findings.length} issue(s) detected`,
      "═".repeat(52),
      "",
      "EXECUTIVE SUMMARY",
      "─".repeat(52),
      result.summary,
      "",
      "SECURITY FINDINGS",
      "─".repeat(52),
      ...sorted.flatMap(f => [
        "",
        `▸ [${f.severity}] ${f.title}`,
        `  Category : ${f.category}`,
        f.lines.length ? `  Lines    : ${f.lines.join(", ")}` : "",
        f.cweId       ? `  CWE ID   : ${f.cweId}` : "",
        "",
        "  DESCRIPTION",
        `  ${f.description}`,
        "",
        "  REMEDIATION",
        `  ${f.remediation}`,
        "",
        "─".repeat(52),
      ].filter(Boolean)),
      ...(result.gasOptimizations?.length ? [
        "",
        "GAS OPTIMIZATIONS",
        "─".repeat(52),
        ...result.gasOptimizations.map((o, i) => `  ${i + 1}. ${o}`),
      ] : []),
      "",
      "═".repeat(52),
      "  Generated by Hawkeye · hawkeye.app",
      "═".repeat(52),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `hawkeye-${result.contractName.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}.txt`;
    a.click();
  };

  return (
    <div className="h-full flex flex-col">
      {/* Risk banner */}
      <div className="shrink-0 rounded-xl p-5 mb-4"
        style={{ background: riskCfg.bg, border: `1px solid ${riskCfg.border}` }}>
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex items-center gap-2.5">
            {result.riskScore === "SAFE"
              ? <ShieldCheck size={18} style={{ color: riskCfg.color }} />
              : <AlertTriangle size={18} style={{ color: riskCfg.color }} />}
            <div>
              <div className="flex items-center gap-2.5">
                <span className="text-[15px] font-bold" style={{ color: riskCfg.color, fontFamily: "'Fraunces', serif" }}>
                  {riskCfg.label}
                </span>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded"
                  style={{ background: "white", color: "#64748B", border: "1px solid #E2E8F0" }}>
                  {result.contractName}
                </span>
              </div>
            </div>
          </div>
          <button onClick={handleExport}
            className="btn-ghost shrink-0 px-3 py-1.5 rounded-lg text-xs">
            <Download size={11} /> Export report
          </button>
        </div>

        <p className="text-[12.5px] leading-relaxed mb-4" style={{ color: "#475569" }}>
          {result.summary}
        </p>

        <div className="flex items-center gap-2 flex-wrap">
          <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold"
            style={{ background: "white", color: "#0B1F3A", border: "1px solid #E2E8F0" }}>
            <FileText size={10} />
            {result.findings.length} finding{result.findings.length !== 1 ? "s" : ""}
          </div>
          {severityOrder.map(sev => counts[sev] ? (
            <div key={sev}
              className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-xs font-semibold"
              style={{ color: SEVERITY_CONFIG[sev].color, background: SEVERITY_CONFIG[sev].bg, border: `1px solid ${SEVERITY_CONFIG[sev].border}` }}>
              <span className="w-1.5 h-1.5 rounded-full" style={{ background: SEVERITY_CONFIG[sev].color }} />
              {counts[sev]} {SEVERITY_CONFIG[sev].label}
            </div>
          ) : null)}
          <div className="ml-auto flex items-center gap-1 text-[11px]" style={{ color: "#CBD5E1" }}>
            <Clock size={10} />
            {new Date(result.timestamp).toLocaleTimeString()}
          </div>
        </div>
      </div>

      {/* Findings */}
      <div className="flex-1 overflow-y-auto space-y-2.5 pr-0.5">
        {sorted.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 gap-3">
            <CheckCircle size={26} style={{ color: "#16A34A" }} />
            <p className="text-sm font-semibold" style={{ color: "#334155" }}>No vulnerabilities detected</p>
            <p className="text-xs" style={{ color: "#94A3B8" }}>Contract passed all security checks</p>
          </div>
        ) : (
          <>
            <div className="flex items-center gap-3 mb-1">
              <span className="text-[9px] font-bold uppercase tracking-widest" style={{ color: "#94A3B8" }}>
                Security Findings
              </span>
              <div style={{ flex: 1, height: 1, background: "#F1F5F9" }} />
            </div>
            {sorted.map((f, i) => <FindingCard key={f.id} finding={f} index={i} />)}
          </>
        )}

        {result.gasOptimizations?.length ? (
          <div className="rounded-xl bg-white p-4 mt-1" style={{ border: "1px solid #E2E8F0" }}>
            <div className="flex items-center gap-2 mb-3">
              <Zap size={12} style={{ color: "#2563A8" }} />
              <span className="text-[9px] font-bold uppercase tracking-widest" style={{ color: "#94A3B8" }}>
                Gas Optimizations
              </span>
            </div>
            <ul className="space-y-3">
              {result.gasOptimizations.map((opt, i) => (
                <li key={i} className="flex gap-3 text-[12.5px]" style={{ color: "#475569" }}>
                  <span className="shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-[9px] font-bold mt-0.5"
                    style={{ background: "#E8F2FA", color: "#2563A8" }}>
                    {i + 1}
                  </span>
                  <span className="leading-relaxed">{opt}</span>
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </div>
    </div>
  );
}