"use client";

import { useState } from "react";
import { AuditResult, SEVERITY_CONFIG, RISK_CONFIG, Severity } from "../types";
import FindingCard from "./FindingCard";
import TweetThread from "./TweetThread";
import { exportToPDF } from "./PdfExport";
import { Download, CheckCircle, AlertTriangle, Clock, Zap, FileText, ShieldCheck, FileDown } from "lucide-react";

const TwitterIcon = ({ size = 12, style }: { size?: number; style?: React.CSSProperties }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" style={style}>
    <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.744l7.737-8.835L1.254 2.25H8.08l4.253 5.622zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
  </svg>
);

export default function AuditReport({ result }: { result: AuditResult }) {
  const riskCfg = RISK_CONFIG[result.riskScore];
  const severityOrder: Severity[] = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];
  const sorted = [...result.findings].sort(
    (a, b) => severityOrder.indexOf(a.severity) - severityOrder.indexOf(b.severity)
  );
  const counts = result.findings.reduce((acc, f) => {
    acc[f.severity] = (acc[f.severity] || 0) + 1;
    return acc;
  }, {} as Record<Severity, number>);

  const [showThread, setShowThread] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);

  const handleExportTxt = () => {
    const lines = [
      "═".repeat(52),
      "  HAWKEYE SECURITY AUDIT REPORT",
      "═".repeat(52),
      `  Contract  : ${result.contractName}`,
      `  Risk Level: ${result.riskScore}`,
      `  Generated : ${new Date(result.timestamp).toLocaleString()}`,
      `  Findings  : ${result.findings.length} issue(s) detected`,
      "═".repeat(52),
      "",
      "EXECUTIVE SUMMARY",
      "─".repeat(52),
      result.summary,
      "",
      "SECURITY FINDINGS",
      "─".repeat(52),
      ...sorted.flatMap(f => [
        "",
        `▸ [${f.severity}] ${f.title}`,
        `  Category : ${f.category}`,
        f.lines.length ? `  Lines    : ${f.lines.join(", ")}` : "",
        f.cweId       ? `  CWE ID   : ${f.cweId}` : "",
        "",
        "  DESCRIPTION",
        `  ${f.description}`,
        "",
        "  REMEDIATION",
        `  ${f.remediation}`,
        "",
        "─".repeat(52),
      ].filter(Boolean)),
      ...(result.gasOptimizations?.length ? [
        "",
        "GAS OPTIMIZATIONS",
        "─".repeat(52),
        ...result.gasOptimizations.map((o, i) => `  ${i + 1}. ${o}`),
      ] : []),
      "",
      "═".repeat(52),
      "  Generated by Hawkeye · hawkeye-sable.vercel.app",
      "═".repeat(52),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `hawkeye-${result.contractName.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}.txt`;
    a.click();
  };

  const handleExportPdf = async () => {
    setPdfLoading(true);
    try {
      await exportToPDF(result);
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <div style={{ height: "100%", display: "flex", flexDirection: "column" }}>

      {showThread && (
        <TweetThread result={result} onClose={() => setShowThread(false)} />
      )}

      {/* ── Risk header ── */}
      <div style={{
        flexShrink: 0, borderRadius: 12, padding: "20px 20px 16px",
        marginBottom: 16, background: riskCfg.bg, border: `1px solid ${riskCfg.border}`,
      }}>
        {/* Top row */}
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 14 }}>
          <div style={{ display: "flex", alignItems: "flex-start", gap: 12 }}>
            <div style={{
              width: 40, height: 40, borderRadius: 10, flexShrink: 0,
              display: "flex", alignItems: "center", justifyContent: "center",
              background: "white", border: `1px solid ${riskCfg.border}`,
            }}>
              {result.riskScore === "SAFE"
                ? <ShieldCheck size={18} style={{ color: riskCfg.color }} />
                : <AlertTriangle size={18} style={{ color: riskCfg.color }} />}
            </div>
            <div>
              <div style={{
                fontFamily: "'Fraunces', Georgia, serif",
                fontSize: 18, fontWeight: 600,
                color: riskCfg.color, lineHeight: 1.2, marginBottom: 5,
              }}>
                {riskCfg.label}
              </div>
              <div style={{
                display: "inline-flex", alignItems: "center", gap: 5,
                fontSize: 11, fontFamily: "'JetBrains Mono', monospace",
                color: "#64748B", background: "white",
                border: "1px solid #E2E8F0", borderRadius: 6, padding: "2px 8px",
              }}>
                <FileText size={10} />
                {result.contractName}
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div style={{ display: "flex", alignItems: "center", gap: 6, flexShrink: 0 }}>
            {/* Tweet thread */}
            <button
              onClick={() => setShowThread(true)}
              style={{
                display: "flex", alignItems: "center", gap: 5,
                fontSize: 12, fontWeight: 500, color: "#1D4ED8",
                background: "#EFF6FF", border: "1px solid #BFDBFE",
                borderRadius: 8, padding: "7px 11px", cursor: "pointer",
                whiteSpace: "nowrap" as const,
              }}
            >
              <TwitterIcon size={12} /> Thread
            </button>

            {/* PDF export */}
            <button
              onClick={handleExportPdf}
              disabled={pdfLoading}
              style={{
                display: "flex", alignItems: "center", gap: 5,
                fontSize: 12, fontWeight: 500, color: "#64748B",
                background: "white", border: "1px solid #E2E8F0",
                borderRadius: 8, padding: "7px 11px", cursor: "pointer",
                whiteSpace: "nowrap" as const,
              }}
            >
              <FileDown size={12} />
              {pdfLoading ? "Generating…" : "PDF"}
            </button>

            {/* TXT export */}
            <button
              onClick={handleExportTxt}
              style={{
                display: "flex", alignItems: "center", gap: 5,
                fontSize: 12, fontWeight: 500, color: "#64748B",
                background: "white", border: "1px solid #E2E8F0",
                borderRadius: 8, padding: "7px 11px", cursor: "pointer",
                whiteSpace: "nowrap" as const,
              }}
            >
              <Download size={12} /> TXT
            </button>
          </div>
        </div>

        {/* Summary */}
        <p style={{ fontSize: 13.5, lineHeight: 1.7, color: "#475569", marginBottom: 16 }}>
          {result.summary}
        </p>

        {/* Pills */}
        <div style={{ display: "flex", flexWrap: "wrap" as const, gap: 8, alignItems: "center" }}>
          <div style={{
            display: "inline-flex", alignItems: "center", gap: 6,
            fontSize: 12, fontWeight: 600, padding: "5px 12px", borderRadius: 8,
            background: "white", border: "1px solid #E2E8F0", color: "#334155",
          }}>
            <FileText size={11} />
            {result.findings.length} finding{result.findings.length !== 1 ? "s" : ""}
          </div>

          {severityOrder.map(sev => counts[sev] ? (
            <div key={sev} style={{
              display: "inline-flex", alignItems: "center", gap: 6,
              fontSize: 12, fontWeight: 600, padding: "5px 12px", borderRadius: 8,
              color: SEVERITY_CONFIG[sev].color,
              background: SEVERITY_CONFIG[sev].bg,
              border: `1px solid ${SEVERITY_CONFIG[sev].border}`,
            }}>
              <span style={{ width: 6, height: 6, borderRadius: "50%", background: SEVERITY_CONFIG[sev].color, display: "inline-block" }} />
              {counts[sev]} {SEVERITY_CONFIG[sev].label}
            </div>
          ) : null)}

          <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 4, fontSize: 11, color: "#CBD5E1" }}>
            <Clock size={10} />
            {new Date(result.timestamp).toLocaleTimeString()}
          </div>
        </div>
      </div>

      {/* ── Findings ── */}
      <div style={{ flex: 1, overflowY: "auto", paddingRight: 2 }}>
        {sorted.length === 0 ? (
          <div style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "48px 0", gap: 12 }}>
            <CheckCircle size={28} style={{ color: "#16A34A" }} />
            <p style={{ fontSize: 14, fontWeight: 600, color: "#334155" }}>No vulnerabilities detected</p>
            <p style={{ fontSize: 12, color: "#94A3B8" }}>Contract passed all security checks</p>
          </div>
        ) : (
          <>
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
              <span style={{ fontSize: 10, fontWeight: 700, textTransform: "uppercase" as const, letterSpacing: "0.1em", color: "#94A3B8", whiteSpace: "nowrap" as const }}>
                Security Findings
              </span>
              <div style={{ flex: 1, height: 1, background: "#F1F5F9" }} />
            </div>
            {sorted.map((f, i) => <FindingCard key={f.id} finding={f} index={i} />)}
          </>
        )}

        {result.gasOptimizations?.length ? (
          <div style={{
            marginTop: 4, background: "#F8FAFC",
            border: "1px solid #E2E8F0", borderRadius: 12, padding: 16,
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 14 }}>
              <Zap size={13} style={{ color: "#2563A8" }} />
              <span style={{ fontSize: 10, fontWeight: 700, textTransform: "uppercase" as const, letterSpacing: "0.1em", color: "#94A3B8" }}>
                Gas Optimizations
              </span>
            </div>
            <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
              {result.gasOptimizations.map((opt, i) => (
                <li key={i} style={{ display: "flex", gap: 12, marginBottom: i < result.gasOptimizations!.length - 1 ? 12 : 0, alignItems: "flex-start" }}>
                  <span style={{
                    width: 22, height: 22, borderRadius: "50%", flexShrink: 0,
                    background: "#E8F2FA", color: "#2563A8",
                    fontSize: 11, fontWeight: 700,
                    display: "flex", alignItems: "center", justifyContent: "center",
                    marginTop: 1,
                  }}>
                    {i + 1}
                  </span>
                  <span style={{ fontSize: 13, lineHeight: 1.65, color: "#475569" }}>{opt}</span>
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </div>
    </div>
  );
}