import { AuditResult, SEVERITY_CONFIG } from "../types";

const SEVERITY_COLORS: Record<string, { r: number; g: number; b: number }> = {
  CRITICAL: { r: 220, g: 38,  b: 38  },
  HIGH:     { r: 194, g: 65,  b: 12  },
  MEDIUM:   { r: 217, g: 119, b: 6   },
  LOW:      { r: 22,  g: 163, b: 74  },
  INFO:     { r: 37,  g: 99,  b: 235 },
};

function hexToRgb(hex: string) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return { r, g, b };
}

export async function exportToPDF(result: AuditResult) {
  // Dynamically import jsPDF to avoid SSR issues
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  const margin = 20;
  const contentW = W - margin * 2;
  let y = 0;

  const addPage = () => {
    doc.addPage();
    y = margin;
    // Footer on each page
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by Hawkeye · hawkeye-sable.vercel.app", margin, 287);
    doc.text(`Page ${doc.getNumberOfPages()}`, W - margin, 287, { align: "right" });
  };

  const checkY = (needed: number) => {
    if (y + needed > 270) addPage();
  };

  // ── COVER PAGE ──────────────────────────────────────
  // Top bar
  doc.setFillColor(11, 31, 58);
  doc.rect(0, 0, W, 8, "F");

  y = 40;

  // Title
  doc.setFontSize(28);
  doc.setTextColor(11, 31, 58);
  doc.setFont("helvetica", "bold");
  doc.text("Security Audit", margin, y);
  y += 10;
  doc.setFontSize(28);
  doc.setTextColor(37, 99, 168);
  doc.text("Report", margin, y);
  y += 16;

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, y, W - margin, y);
  y += 12;

  // Contract info
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.text("CONTRACT", margin, y);
  y += 6;
  doc.setFontSize(14);
  doc.setTextColor(11, 31, 58);
  doc.setFont("helvetica", "bold");
  doc.text(result.contractName, margin, y);
  y += 12;

  // Risk score badge
  const riskColor = SEVERITY_COLORS[result.riskScore] || SEVERITY_COLORS.INFO;
  doc.setFillColor(riskColor.r, riskColor.g, riskColor.b);
  doc.roundedRect(margin, y, 40, 10, 2, 2, "F");
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(`${result.riskScore} RISK`, margin + 20, y + 6.5, { align: "center" });
  y += 18;

  // Meta info
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated: ${new Date(result.timestamp).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`, margin, y);
  y += 6;
  doc.text(`Total findings: ${result.findings.length}`, margin, y);
  y += 16;

  // Summary box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  const summaryLines = doc.splitTextToSize(result.summary, contentW - 16) as string[];
  const summaryH = summaryLines.length * 5.5 + 14;
  doc.roundedRect(margin, y, contentW, summaryH, 3, 3, "FD");
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "bold");
  doc.text("EXECUTIVE SUMMARY", margin + 8, y + 8);
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "normal");
  doc.text(summaryLines, margin + 8, y + 16);
  y += summaryH + 12;

  // Severity breakdown
  const severities = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"] as const;
  const counts = result.findings.reduce((acc, f) => {
    acc[f.severity] = (acc[f.severity] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const colW = contentW / 5;
  severities.forEach((sev, i) => {
    const x = margin + i * colW;
    const color = SEVERITY_COLORS[sev];
    doc.setFillColor(color.r, color.g, color.b);
    doc.setFillColor(
      Math.round(color.r + (255 - color.r) * 0.88),
      Math.round(color.g + (255 - color.g) * 0.88),
      Math.round(color.b + (255 - color.b) * 0.88)
    );
    doc.roundedRect(x, y, colW - 3, 18, 2, 2, "F");
    doc.setFontSize(16);
    doc.setTextColor(color.r, color.g, color.b);
    doc.setFont("helvetica", "bold");
    doc.text(String(counts[sev] || 0), x + (colW - 3) / 2, y + 9, { align: "center" });
    doc.setFontSize(7);
    doc.setTextColor(color.r, color.g, color.b);
    doc.setFont("helvetica", "normal");
    doc.text(sev, x + (colW - 3) / 2, y + 15, { align: "center" });
  });
  y += 26;

  // ── FINDINGS PAGES ──────────────────────────────────
  addPage();

  // Section header
  doc.setFontSize(16);
  doc.setTextColor(11, 31, 58);
  doc.setFont("helvetica", "bold");
  doc.text("Security Findings", margin, y);
  y += 4;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, W - margin, y);
  y += 10;

  // Sort findings
  const sorted = [...result.findings].sort(
    (a, b) => severities.indexOf(a.severity as any) - severities.indexOf(b.severity as any)
  );

  sorted.forEach((finding, idx) => {
    const color = SEVERITY_COLORS[finding.severity];
    const descLines = doc.splitTextToSize(finding.description, contentW - 16) as string[];
    const remedLines = doc.splitTextToSize(finding.remediation, contentW - 16) as string[];
    const cardH = 10 + 6 + descLines.length * 5 + 8 + remedLines.length * 5 + 14;

    checkY(cardH + 4);

    // Accent bar
    doc.setFillColor(color.r, color.g, color.b);
    doc.rect(margin, y, 3, cardH, "F");

    // Card background
    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.rect(margin + 3, y, contentW - 3, cardH, "FD");

    const cx = margin + 10;
    let cy = y + 8;

    // Severity badge
    doc.setFillColor(
      Math.round(color.r + (255 - color.r) * 0.88),
      Math.round(color.g + (255 - color.g) * 0.88),
      Math.round(color.b + (255 - color.b) * 0.88)
    );
    doc.roundedRect(cx, cy - 4, 22, 7, 1, 1, "F");
    doc.setFontSize(7);
    doc.setTextColor(color.r, color.g, color.b);
    doc.setFont("helvetica", "bold");
    doc.text(finding.severity, cx + 11, cy + 0.5, { align: "center" });

    // Title
    doc.setFontSize(11);
    doc.setTextColor(11, 31, 58);
    doc.setFont("helvetica", "bold");
    doc.text(finding.title, cx + 26, cy);
    cy += 7;

    // Meta
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "normal");
    const meta: string[] = [];
    if (finding.lines.length) meta.push(`Lines: ${finding.lines.join(", ")}`);
    meta.push(finding.category);
    if (finding.cweId) meta.push(finding.cweId);
    doc.text(meta.join("  ·  "), cx, cy);
    cy += 8;

    // Description label
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.setFont("helvetica", "bold");
    doc.text("WHAT'S THE ISSUE", cx, cy);
    cy += 5;

    // Description
    doc.setFontSize(9.5);
    doc.setTextColor(71, 85, 105);
    doc.setFont("helvetica", "normal");
    doc.text(descLines, cx, cy);
    cy += descLines.length * 5 + 6;

    // Remediation label
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.setFont("helvetica", "bold");
    doc.text("HOW TO FIX IT", cx, cy);
    cy += 5;

    // Remediation
    doc.setFontSize(9.5);
    doc.setTextColor(71, 85, 105);
    doc.setFont("helvetica", "normal");
    doc.text(remedLines, cx, cy);

    y += cardH + 6;
  });

  // ── GAS OPTIMIZATIONS ───────────────────────────────
  if (result.gasOptimizations?.length) {
    checkY(30);
    y += 4;
    doc.setFontSize(14);
    doc.setTextColor(11, 31, 58);
    doc.setFont("helvetica", "bold");
    doc.text("Gas Optimizations", margin, y);
    y += 4;
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, y, W - margin, y);
    y += 8;

    result.gasOptimizations.forEach((opt, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${opt}`, contentW) as string[];
      checkY(lines.length * 5 + 4);
      doc.setFontSize(10);
      doc.setTextColor(71, 85, 105);
      doc.setFont("helvetica", "normal");
      doc.text(lines, margin, y);
      y += lines.length * 5 + 4;
    });
  }

  // Final footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by Hawkeye · hawkeye-sable.vercel.app", margin, 287);
  doc.text(`Page ${doc.getNumberOfPages()}`, W - margin, 287, { align: "right" });

  // Save
  doc.save(`hawkeye-${result.contractName.toLowerCase().replace(/\s+/g, "-")}-${Date.now()}.pdf`);
}